version: "3.8"

services:

  backend:
    build: ./backend
    container_name: ikenna-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: ikenna_user
      DB_PASSWORD: strongpassword
      DB_NAME: ikenna_db
    networks:
      - ikenna-net

  mysql:
    image: mysql:8
    container_name: ikenna-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongrootpassword
      MYSQL_DATABASE: ikenna_db
      MYSQL_USER: ikenna_user
      MYSQL_PASSWORD: strongpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ikenna-net

  frontend:
    build: ./frontend
    container_name: ikenna-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ikenna-net

networks:
  ikenna-net:

volumes:
  mysql-data:
