version: "3.8"

services:

  nginx:
    image: nginx:stable-alpine
    container_name: ikenna-nginx
    restart: always

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - frontend
      - backend

    networks:
      - ikenna-net

    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: ikenna-nginx
        awslogs-stream: nginx

 backend:
    build: ./backend
    container_name: ikenna-backend
    restart: always

    volumes:
      - ./backend/logs:/app/logs

    expose:
      - "5000"

    env_file:
      - ./backend/.env

    depends_on:
      - mysql

    networks:
      - ikenna-net

    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: ikenna-backend
        awslogs-stream: backend


  frontend:
    build: ./frontend
    container_name: ikenna-frontend
    restart: always

    expose:
      - "80"

    depends_on:
      - backend

    networks:
      - ikenna-net

    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: ikenna-frontend
        awslogs-stream: frontend

  mysql:
    image: mysql:8
    container_name: ikenna-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: strongrootpassword
      MYSQL_DATABASE: ikenna_db
      MYSQL_USER: ikenna_user
      MYSQL_PASSWORD: strongpassword

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - ikenna-net

    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: ikenna-mysql
        awslogs-stream: mysql

networks:
  ikenna-net:

volumes:
  mysql-data:
