server {
    listen 80;

    access_log /dev/stdout;
    error_log /dev/stderr;

    location / {
        proxy_pass http://ikenna-frontend:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://ikenna-backend:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
